-- Run migrations with a privileged migration role. The runtime role must not own
-- these tables and must not have BYPASSRLS; RLS below is the tenant safety net.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE schools (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text NOT NULL, timezone text NOT NULL DEFAULT 'Asia/Kolkata', currency char(3) NOT NULL DEFAULT 'INR',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','archived')), settings jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE campuses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), name text NOT NULL, address jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id, name));
CREATE TABLE academic_years (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), name text NOT NULL, starts_on date NOT NULL, ends_on date NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','active','closed')), UNIQUE(school_id,name), CHECK(ends_on > starts_on));
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email citext NOT NULL UNIQUE, password_hash text NOT NULL, name text NOT NULL, phone text, status text NOT NULL DEFAULT 'invited' CHECK(status IN ('invited','active','locked','disabled')), email_verified_at timestamptz, last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), user_id uuid NOT NULL REFERENCES users(id), role text NOT NULL CHECK(role IN ('student','guardian','teacher','finance','admin','platform_support')), status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id,user_id,role));
CREATE TABLE students (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), admission_no text NOT NULL, legal_name text NOT NULL, date_of_birth date, gender text, status text NOT NULL DEFAULT 'active' CHECK(status IN ('applicant','active','withdrawn','graduated')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id,admission_no));
CREATE TABLE guardians (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), user_id uuid REFERENCES users(id), legal_name text NOT NULL, relationship text NOT NULL, phone text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE student_guardians (school_id uuid NOT NULL REFERENCES schools(id), student_id uuid NOT NULL REFERENCES students(id), guardian_id uuid NOT NULL REFERENCES guardians(id), is_primary boolean NOT NULL DEFAULT false, PRIMARY KEY(student_id,guardian_id));
CREATE TABLE staff (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), user_id uuid REFERENCES users(id), employee_no text NOT NULL, designation text, joined_on date, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive','terminated')), UNIQUE(school_id,employee_no));
CREATE TABLE classes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), name text NOT NULL, UNIQUE(school_id,academic_year_id,name));
CREATE TABLE sections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), class_id uuid NOT NULL REFERENCES classes(id), name text NOT NULL, UNIQUE(class_id,name));
CREATE TABLE subjects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), code text NOT NULL, name text NOT NULL, UNIQUE(school_id,code));
CREATE TABLE enrollments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), student_id uuid NOT NULL REFERENCES students(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), section_id uuid NOT NULL REFERENCES sections(id), roll_no text, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','transferred','withdrawn')), UNIQUE(school_id,student_id,academic_year_id));
CREATE TABLE attendance_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), enrollment_id uuid NOT NULL REFERENCES enrollments(id), attendance_date date NOT NULL, status text NOT NULL CHECK(status IN ('present','absent','late','leave')), recorded_by uuid REFERENCES users(id), approved_by uuid REFERENCES users(id), recorded_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(school_id,enrollment_id,attendance_date));
CREATE TABLE assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), academic_year_id uuid NOT NULL REFERENCES academic_years(id), subject_id uuid NOT NULL REFERENCES subjects(id), name text NOT NULL, max_marks numeric(8,2) NOT NULL CHECK(max_marks > 0), published_at timestamptz);
CREATE TABLE grades (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), assessment_id uuid NOT NULL REFERENCES assessments(id), enrollment_id uuid NOT NULL REFERENCES enrollments(id), marks numeric(8,2) NOT NULL CHECK(marks >= 0), status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','approved','published')), entered_by uuid REFERENCES users(id), approved_by uuid REFERENCES users(id), approved_at timestamptz, UNIQUE(assessment_id,enrollment_id));
CREATE TABLE invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), student_id uuid NOT NULL REFERENCES students(id), invoice_no text NOT NULL, issued_on date NOT NULL, due_on date NOT NULL, currency char(3) NOT NULL DEFAULT 'INR', total_paise bigint NOT NULL CHECK(total_paise >= 0), status text NOT NULL DEFAULT 'open' CHECK(status IN ('draft','open','paid','void','refunded')), created_by uuid REFERENCES users(id), UNIQUE(school_id,invoice_no));
CREATE TABLE payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), invoice_id uuid REFERENCES invoices(id), amount_paise bigint NOT NULL CHECK(amount_paise > 0), currency char(3) NOT NULL DEFAULT 'INR', provider text NOT NULL, provider_reference text, status text NOT NULL CHECK(status IN ('pending','succeeded','failed','refunded')), received_at timestamptz, recorded_by uuid REFERENCES users(id), UNIQUE(school_id,provider,provider_reference));
CREATE TABLE payroll_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), period_start date NOT NULL, period_end date NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','approved','paid','cancelled')), approved_by uuid REFERENCES users(id), approved_at timestamptz, UNIQUE(school_id,period_start,period_end));
CREATE TABLE payroll_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), payroll_run_id uuid NOT NULL REFERENCES payroll_runs(id), staff_id uuid NOT NULL REFERENCES staff(id), gross_paise bigint NOT NULL, deductions_paise bigint NOT NULL DEFAULT 0, net_paise bigint NOT NULL, UNIQUE(payroll_run_id,staff_id));
CREATE TABLE documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id), owner_type text NOT NULL, owner_id uuid NOT NULL, storage_key text NOT NULL UNIQUE, original_name text NOT NULL, content_type text NOT NULL, size_bytes bigint NOT NULL CHECK(size_bytes >= 0), malware_status text NOT NULL DEFAULT 'pending' CHECK(malware_status IN ('pending','clean','infected','failed')), uploaded_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), school_id uuid NOT NULL REFERENCES schools(id), token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, revoked_at timestamptz, ip_address inet, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE password_reset_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events (id bigserial PRIMARY KEY, school_id uuid NOT NULL REFERENCES schools(id), actor_id uuid REFERENCES users(id), action text NOT NULL, entity_type text NOT NULL, entity_id uuid, before_data jsonb, after_data jsonb, request_id text, ip_address inet, occurred_at timestamptz NOT NULL DEFAULT now());

-- The application role can append audit events but cannot rewrite history.
CREATE FUNCTION prevent_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit events are immutable'; END; $$;
CREATE TRIGGER audit_events_immutable BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();

CREATE INDEX ON memberships (school_id, user_id) WHERE status = 'active';
CREATE INDEX ON attendance_records (school_id, attendance_date);
CREATE INDEX ON grades (school_id, assessment_id);
CREATE INDEX ON invoices (school_id, student_id, status);
CREATE INDEX ON audit_events (school_id, occurred_at DESC);

-- Tenant isolation: runtime calls must use `db.withTenant(schoolId, ...)`.
DO $$ DECLARE table_name text; BEGIN
  FOREACH table_name IN ARRAY ARRAY['campuses','academic_years','memberships','students','guardians','student_guardians','staff','classes','sections','subjects','enrollments','attendance_records','assessments','grades','invoices','payments','payroll_runs','payroll_entries','documents','sessions','audit_events'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (school_id = current_setting(''app.tenant_id'', true)::uuid) WITH CHECK (school_id = current_setting(''app.tenant_id'', true)::uuid)', table_name);
  END LOOP;
END $$;
